name: Demo K8s Workflow

env:
  IMAGE_TAG: ${{ github.run_number }}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          tags: frdevelopergen/react-app-nginx:${{ env.IMAGE_TAG }}
          

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: frdevelopergen/react-app-nginx:${{ env.IMAGE_TAG }}
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl 
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig 
        run: aws eks update-kubeconfig --name example-k8s --region us-east-1

      - name: Upgrade app with new features
        run: |
          helm upgrade example-k8s .helm  --set app_container_tag=${{ env.IMAGE_TAG }}