name: Docker Publish
on: workflow_dispatch
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: centosadmin/kubernetes-helm:latest
        with:
          version: 'latest'

      - name: Get nodes
        run: |
          kubectl get nodes
