name: Demo K8s Workflow

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
      IMAGE_NAME: frdevelopergen/react-app-nginx
    steps:
      - name: Echo]
        run: |
           echo "$IMAGE_NAME:$IMAGE_TAG"